-- Migration number: 0001 	 2026-09-21T04:00:08.558Z
--
-- SQLite/D1 translation of apps/rareAppMn/rareAppMn-service/prisma/schema.prisma
-- (Postgres). Key dialect differences from the Postgres source of truth:
--   - id columns: TEXT primary keys, no DB-side default (Postgres used
--     gen_random_uuid()); ids must be generated by application code before
--     insert when writing to this database.
--   - Boolean columns: INTEGER (0/1), matching SQLite's lack of a native
--     boolean type.
--   - DateTime columns: TEXT (ISO-8601 / SQLite's CURRENT_TIMESTAMP format);
--     updatedAt is not auto-refreshed on UPDATE (no trigger defined) and
--     must be set by application code, same as the Postgres @updatedAt
--     behavior is emulated at the Prisma layer, not the DB layer, here.
--   - Float column (minimumScore): REAL.

PRAGMA foreign_keys = ON;

CREATE TABLE "University" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "shortName" TEXT,
  "description" TEXT,
  "logo" TEXT,
  "website" TEXT,
  "type" TEXT,
  "location" TEXT,
  "address" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "foundedYear" INTEGER,
  "isActive" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Faculty" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "universityId" TEXT NOT NULL REFERENCES "University"("id") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Faculty_universityId_idx" ON "Faculty"("universityId");

CREATE TABLE "Program" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "universityId" TEXT NOT NULL REFERENCES "University"("id") ON DELETE CASCADE,
  "facultyId" TEXT NOT NULL REFERENCES "Faculty"("id") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "degree" TEXT NOT NULL,
  "duration" TEXT,
  "description" TEXT,
  "language" TEXT,
  "isActive" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Program_universityId_idx" ON "Program"("universityId");
CREATE INDEX "Program_facultyId_idx" ON "Program"("facultyId");

CREATE TABLE "AdmissionRequirement" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "programId" TEXT NOT NULL REFERENCES "Program"("id") ON DELETE CASCADE,
  "academicYear" TEXT NOT NULL,
  "minimumScore" REAL,
  "description" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "AdmissionRequirement_programId_idx" ON "AdmissionRequirement"("programId");

CREATE TABLE "Subject" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL UNIQUE,
  "createdAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Join table for the AdmissionRequirement <-> Subject many-to-many relationship.
CREATE TABLE "AdmissionRequirementSubject" (
  "admissionRequirementId" TEXT NOT NULL REFERENCES "AdmissionRequirement"("id") ON DELETE CASCADE,
  "subjectId" TEXT NOT NULL REFERENCES "Subject"("id") ON DELETE CASCADE,
  PRIMARY KEY ("admissionRequirementId", "subjectId")
);
CREATE INDEX "AdmissionRequirementSubject_subjectId_idx" ON "AdmissionRequirementSubject"("subjectId");
